### ISSUE TITLE
sample config file if possible

### ISSUE THREAD

**Issue by Neue-Ziel** [Azure/azure-relay-bridge#2]
would you provide a sample config file so that we may test different parameters.

**Comment by jnettleton** [comment]
For a SQL server test, you can use:

On clientHost (SSMS installed):

LocalForward :
  - BindAddress: clientHost
    BindPort: 1433
    RelayName: my-relay-sqldb

On serverHost (SQL Server installed):

RemoteForward :
  - Host: serverHost
    HostPort: 1433
    RelayName: my-relay-sqldb

on both hosts, add your relay information:

# RELAY KEY
AzureRelayConnectionString : "Endpoint=sb://my-relay.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=***************"
AzureRelayEndpoint : "sb://my-relay.servicebus.windows.net/"
AzureRelaySharedAccessKeyName : "RootManageSharedAccessKey"
AzureRelaySharedAccessKey : "***************"
