### ISSUE TITLE
0.6.2 missing changelog

### ISSUE THREAD

**Issue by bewatersmsft** [Azure/azure-relay-bridge#52]
Were there any major changes in the 0.6.2 release?

**Comment by clemensv** [comment]
"Sorry about our apperance" is what they put on the construction site signs, right? I've been doing a pretty thorough cleanup in the past two weeks. I will put a proper change log into 0.7.0. 

There should be no significant functional changes if you've been using the tool before. 

The -R option has been replaced by -T with a more logical syntax, but -R has been preserved. There's now -H to set up HTTP listeners with reverse proxy functionality. You can use an ambient AAD credential if you use -e for the endpoint without giving a connection string or a SAS rule name. The tool now runs on .NET 6.0 on all platforms.
