### ISSUE TITLE
Typo in RelayBridgeService.cs

### ISSUE THREAD

**Issue by PhilArundell** [Azure/azure-relay-bridge#6]
On line 45 you have
   $"Mirosoft\\Azure Relay Bridge\\azbridge_config.svc.yml");

When it should be
   $"Microsoft\\Azure Relay Bridge\\azbridge_config.svc.yml");

The net result of this is that when running as a service, it's looking in the wrong directory for its config file - it is looking in C:\ProgramData\Mirosoft\Azure Relay Bridge rather than C:\ProgramData\Microsoft\Azure Relay Bridge (and the former isn't created by the installer)

Manually creating the folder and copying the file over works fine

**Comment by dlstucki** [comment]
Typo fixed and merged. Thank you for reporting it.
