### ISSUE TITLE
Error: FormatException: The format of value 'application/json; charset=utf-8' is invalid.

### ISSUE THREAD

**Issue by sasank-chaganty** [Azure/azure-relay-bridge#66]
Hello,

I've been encountering a persistent issue where if I get a request with the following header sent to my relay endpoint:
`Content-Type`: `application/json; charset=utf-8`

azbridge prints out the following error:
Error: FormatException: The format of value 'application/json; charset=utf-8' is invalid.

![image](https://github.com/Azure/azure-relay-bridge/assets/29584051/72fb6754-9c38-4237-9571-9a07d0ea0c2f)

**Comment by sasank-chaganty** [comment]
Adding more detail for this issue:

Error: `System.FormatException: 'The format of value 'application/json; charset=utf-8' is invalid.'`

```
This exception was originally thrown at this call stack:
    System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(string, string)
    System.Net.Http.Headers.MediaTypeHeaderValue.MediaTypeHeaderValue(string)
    Microsoft.Azure.Relay.Bridge.TcpRemoteForwarder.CreateHttpRequestMessage(Microsoft.Azure.Relay.RelayedHttpListenerContext) in TcpRemoteForwarder.cs
    Microsoft.Azure.Relay.Bridge.TcpRemoteForwarder.HandleRequest(Microsoft.Azure.Relay.RelayedHttpListenerContext) in TcpRemoteForwarder.cs
```

![image](https://github.com/Azure/azure-relay-bridge/assets/29584051/aba3e116-1772-4bed-95ac-7ea46e6adca2)

Failing on this line when `contentType` is `application/json; charset=utf-8`. For some reason, the `MediaTypeHeaderValue` throws an error even though the string is RFC 2616 compliant

![image](https://github.com/Azure/azure-relay-bridge/assets/29584051/63655a48-0762-4f26-b7e5-b29f8382cc36)

Looks like this has been a long-standing issue: https://github.com/dotnet/runtime/issues/20272

Ended up using this work-around from @wjrogers to get unblocked: 

```
var mediaType = MediaTypeHeaderValue.Parse("text/plain; charset=iso-8859-5");
```
![image](https://github.com/Azure/azure-relay-bridge/assets/29584051/e9c93dd6-d77f-4887-873c-636e75a7927e)

**Comment by clemensv** [comment]
That has been fixed
