### ISSUE TITLE
Azure-Relay Is this not planned to be released as official service ?

### ISSUE THREAD

**Issue by hrishikeshgjoshi** [Azure/azure-relay-bridge#69]
Azure -Relay Bridge documentation has following note. Can someone share implementation of following note from documentation where it is mentioned it's not guaranteed reaction time for addressing any such issues. Is it something being replaced by something else or there is planning to stop supporting it. 
NOTE: Azure Relay is a fully supported cloud service that has been around for well over a decade, but this tool is not covered by Azure product support. Issues must be filed here and there is no guaranteed reaction time for addressing any such issues.

**Comment by clemensv** [comment]
This tool is provided as-is. The Relay and its SDK are fully supported. You can call Microsoft product support if you treat this tool as your own code, i.e. you can ask for investigations into the service health and into the SDK implementation, but you're not entitled to help with this project's code. We'll make it known if that changes.
