### ISSUE TITLE
RelayName doesn't support periods

### ISSUE THREAD

**Issue by congyiwu** [Azure/azure-relay-bridge#8]
I was able to create a Hybrid Connection named `foo.bar`.

However, this config:
```
RemoteForward:
- RelayName: codedev.ms
```
Resulted in this error:
> Invalid RelayName value: codedev.ms. Must be a valid relay name expression
> Parameter name: RelayName

The validation regex doesn't support periods:
https://github.com/Azure/azure-relay-bridge/blob/ae0c56399adbcf81d843712974c201f0bc94665b/src/Microsoft.Azure.Relay.Bridge/Configuration/RemoteForward.cs#L60

I can't find any documentation of the actual naming rules for hybrid connections.  I'd expect it to be documented in one of these places:
https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-faq#naming-restrictions
https://docs.microsoft.com/en-us/azure/architecture/best-practices/resource-naming

**Comment by clemensv** [comment]
That is indeed an oversight. Our naming conventions for the messaging services generally rule out periods in names, but the Relay has an exception here. I will fix this.
